/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package kriptic;

import javax.swing.JOptionPane;

/**
 *
 * @author akhfa
 */
public class Kriptic extends javax.swing.JFrame {

    /**
     * Creates new form Kriptic
     */
    public Kriptic() {
        initComponents();
        vigenere_basic_radio.setSelected(true);
        vigenere_basic_radio.setActionCommand("vigenere_basic");
        vigenere_ext_radio.setActionCommand("vigenere_ext");
        playfair_radio.setActionCommand("playfair");
        Enkripsi_grup.add(vigenere_basic_radio);
        Enkripsi_grup.add(vigenere_ext_radio);
        Enkripsi_grup.add(playfair_radio);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Enkripsi_grup = new javax.swing.ButtonGroup();
        jScrollPane1 = new javax.swing.JScrollPane();
        Asal_text = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        Hasil_text = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        Encrypt_button = new javax.swing.JButton();
        Decrypt_button = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        Kunci_textbox = new javax.swing.JTextField();
        vigenere_basic_radio = new javax.swing.JRadioButton();
        vigenere_ext_radio = new javax.swing.JRadioButton();
        playfair_radio = new javax.swing.JRadioButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Asal_text.setColumns(20);
        Asal_text.setLineWrap(true);
        Asal_text.setRows(5);
        jScrollPane1.setViewportView(Asal_text);

        Hasil_text.setEditable(false);
        Hasil_text.setBackground(new java.awt.Color(204, 204, 204));
        Hasil_text.setColumns(20);
        Hasil_text.setLineWrap(true);
        Hasil_text.setRows(5);
        jScrollPane2.setViewportView(Hasil_text);

        jLabel1.setText("Text (Plain / Chiper)");

        jLabel2.setText("Hasil");

        Encrypt_button.setText("Encrypt");
        Encrypt_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Encrypt_buttonActionPerformed(evt);
            }
        });

        Decrypt_button.setText("Decrypt");
        Decrypt_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Decrypt_buttonActionPerformed(evt);
            }
        });

        jLabel3.setText("Kunci");

        vigenere_basic_radio.setText("Vigenere");

        vigenere_ext_radio.setText("Vigenere Ext");

        playfair_radio.setText("Playfair");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Kunci_textbox))
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 394, Short.MAX_VALUE)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(Encrypt_button)
                                .addComponent(Decrypt_button)
                                .addComponent(vigenere_basic_radio)
                                .addComponent(vigenere_ext_radio, javax.swing.GroupLayout.Alignment.TRAILING))
                            .addComponent(playfair_radio)))
                    .addComponent(jLabel2)
                    .addComponent(jLabel1))
                .addContainerGap(13, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(Kunci_textbox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(19, 19, 19)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(Encrypt_button)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Decrypt_button)
                        .addGap(18, 18, 18)
                        .addComponent(vigenere_basic_radio)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(vigenere_ext_radio)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(playfair_radio)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Encrypt_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Encrypt_buttonActionPerformed
        // TODO add your handling code here:
        Enkripsi enc = new Enkripsi(Asal_text.getText(), Kunci_textbox.getText());
        if(Enkripsi_grup.getSelection().getActionCommand().compareTo("vigenere_basic") == 0)
            Hasil_text.setText(enc.vigenere(true, true));
        else if(Enkripsi_grup.getSelection().getActionCommand().compareTo("vigenere_ext") == 0)
            Hasil_text.setText(enc.vigenere(false, true));
        else
            JOptionPane.showMessageDialog(null, "salah");
    }//GEN-LAST:event_Encrypt_buttonActionPerformed

    private void Decrypt_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Decrypt_buttonActionPerformed
        // TODO add your handling code here:
        Enkripsi dec = new Enkripsi(Asal_text.getText(), Kunci_textbox.getText());
        if(Enkripsi_grup.getSelection().getActionCommand().compareTo("vigenere_basic") == 0)
            Hasil_text.setText(dec.vigenere(true, false));
        else if(Enkripsi_grup.getSelection().getActionCommand().compareTo("vigenere_ext") == 0)
            Hasil_text.setText(dec.vigenere(false, false));
        else
            JOptionPane.showMessageDialog(null, "salah");
    }//GEN-LAST:event_Decrypt_buttonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Kriptic.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Kriptic.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Kriptic.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Kriptic.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Kriptic().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea Asal_text;
    private javax.swing.JButton Decrypt_button;
    private javax.swing.JButton Encrypt_button;
    private javax.swing.ButtonGroup Enkripsi_grup;
    private javax.swing.JTextArea Hasil_text;
    private javax.swing.JTextField Kunci_textbox;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JRadioButton playfair_radio;
    private javax.swing.JRadioButton vigenere_basic_radio;
    private javax.swing.JRadioButton vigenere_ext_radio;
    // End of variables declaration//GEN-END:variables
}
